[package]
name = "sendme-gui-tauri-1"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1", features = [] }

[dependencies]
tauri = { version = "1", features = [ "fs-all", "dialog-all", "path-all", "shell-open"] }
tauri = { version = "1", features = [ "fs-all", "dialog-all", "path-all", "shell-open"] }

serde = { version = "1", features = ["derive"] }
serde_json = "1"
async-channel = "2.3.1"
clap = { version = "4.4.10", features = ["derive"] }
console = "0.15.7"
derive_more = { version = "1.0.0", features = [
    "display",
    "from_str"
] }
anyhow = "1.0.75"
futures-buffered = "0.2.4"
futures-lite = "2.3.0"
futures = "0.3"
indicatif = "0.17.7"
iroh-blobs = { version = "0.32", features = ["net_protocol"] }
iroh-io = "0.6"
iroh = "0.32"
num_cpus = "1.16.0"
rand = "0.8.5"
tokio = { version = "1.34.0", features = ["full"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
walkdir = "2.4.0"
data-encoding = "2.6.0"
n0-future = "0.1.2"
dirs = "5.0"
lazy_static = "1.4"
reqwest = { version = "0.11", features = ["json"] }

[features]
# This feature is used for production builds or when a dev server is not specified, DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
